# Generated by Django 4.2.13 on 2024-06-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrudStudent',
            new_name='Student',
        ),
    ]
